# Generated by Django 5.1.1 on 2024-10-11 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
