# Generated by Django 5.1.1 on 2024-09-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank'), ('chapa', 'Chapa')], default='bank', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
