# Generated by Django 5.1.1 on 2024-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='Unique product code', max_length=50, null=True, unique=True),
        ),
    ]
