# Generated by Django 5.1.1 on 2024-10-22 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_telegram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegram',
            options={'verbose_name': 'Telegram Post', 'verbose_name_plural': 'Telegram Posts'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
