# Generated by Django 5.1.1 on 2024-10-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
